bag/urls.py
""" Bag App - urls.py """
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

blog/urls.py
""" Blog App - urls.py """
from django.urls import path
from . import views


urlpatterns = [
    path('', views.blog, name='blog'),
    path('add_post/', views.add_post, name="add_post"),
    path('<int:post_id>/', views.post_detail, name='post_detail'),
    path('edit_post/<int:post_id>/', views.edit_post, name="edit_post"),
    path('delete_post/<int:post_id>/', views.delete_post, name="delete_post"),
    path('delete_comment/<int:comment_id>/',
         views.delete_comment, name="delete_comment"),
]

ms4/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('blog/', include('blog.urls')),
    path('contact/', include('contact.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
""" Blog App - models.py """
from django.db import models


class Post(models.Model):
    """
    Create a blog post
    """
    title = models.CharField(max_length=255)
    body = models.TextField()
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        """
        set the order to display the post
        """
        ordering = ['-date_added']


class Comment(models.Model):
    """
    Submit a comment to a post
    """
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    class Meta:
        """
        Set the order in which comments should be displayed
        """
        ordering = ['date_added']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)

blog/forms.py
""" Blog App - forms.py """
from django import forms
from .widgets import CustomClearableFileInput
from .models import Post, Comment


class PostForm(forms.ModelForm):
    """
    Post Form to render the fields in the form for the blog post.
    """
    class Meta:
        """
        The fields to be used
        """
        model = Post
        fields = ['title', 'body', 'image_url']

    image = forms.ImageField(
        label='Image', required=False, widget=CustomClearableFileInput)


class CommentForm(forms.ModelForm):
    """
    Comment Form to render the fields
    in the form for posting a comment.
    """
    class Meta:
        """
        The fields to be used
        """
        model = Comment
        fields = ['name', 'email', 'body']

blog/views.py
""" Blog App - views.py """
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import Post, Comment
from .forms import CommentForm, PostForm


def blog(request):
    """
    A view to show all the blog posts.
    """
    posts = Post.objects.all()

    return render(request, 'blog/blog.html', {'posts': posts})


def post_detail(request, post_id):
    """
    A view to show more of a selected blog post
    """
    template_name = 'blog/post_detail.html'
    post = get_object_or_404(Post, pk=post_id)
    comments = post.comments.filter(active=True)
    comment_count = post.comments.filter(active=True).count()
    new_comment = None
    # Comment posted
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():

            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    context = {
        'post': post,
        'comments': comments,
        'new_comment': new_comment,
        'comment_form': comment_form,
        'on_blog_page': True,
        'comment_count': comment_count
    }

    return render(request, template_name, context)


@login_required
def add_post(request):
    """
    A view to to allow an admin to add a blog post
    """
    if not request.user.is_superuser:
        messages.error(
            request, 'Sorry, only administrators can add a blog post')
        return redirect(reverse('blog'))

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save()
            form.save()
            messages.info(request, 'Successfully added Blog Post!')
            return redirect(reverse('post_detail', args=[post.id]))
        else:
            messages.error(request,
                           'Could not add post to site. \
                           Please ensure form is valid!')
    else:
        form = PostForm()

    template = 'blog/add_post.html'
    context = {
        'form': form,
        'on_blog_page': True
    }

    return render(request, template, context)


@login_required
def edit_post(request, post_id):
    """
    A view to to allow an admin to edit a blog post
    """
    if not request.user.is_superuser:
        messages.error(request,
                       'Sorry, only the admin can edit a blog post')
        return redirect(reverse('blog'))

    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            data = form.save(commit=False)
            data.user = request.user
            form.save()
            messages.success(request, 'Successfully Updated Blog Post!')
            return redirect(reverse('post_detail', args=[post.id]))
        else:
            messages.error(request,
                           'Could not add post to site. \
                           Please ensure form is valid!')
    else:
        form = PostForm(instance=post)
        messages.info(request, f'You are editing a post titled: {post.title}')

    template = 'blog/edit_post.html'
    context = {
        'form': form,
        'post': post,
        'on_blog_page': True
    }

    return render(request, template, context)


@login_required
def delete_post(request, post_id):
    """
    A view to to allow an admin to delete a blog post
    """
    if not request.user.is_superuser:
        messages.error(
            request, 'Sorry, only the administrator can remove a blog post.')
        return redirect(reverse('blog'))

    selected_post = get_object_or_404(Post, pk=post_id)
    selected_post.delete()
    messages.info(request, 'The Post has been deleted!')

    return redirect(reverse('blog'))


@login_required
def delete_comment(request, comment_id):
    """
    A view to to allow an admin to delete a comment on a post
    """
    if not request.user.is_superuser:
        messages.error(
            request, 'Sorry, only the administrator \
            can remove a comment from a post!')
        return redirect(reverse('blog'))

    else:
        comment = get_object_or_404(Comment, pk=comment_id)
        comment.delete()
        messages.info(request, 'The comment was succesfully deleted!')

        return redirect(reverse('blog'))

blog/templates/blog/add_post.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
<div class="container mb-4">
    <div class="row d-flex justify-content-center">
        <div class="col">
            <h2 class="page-heading-font text-center">Add Post</h2>
            <hr>
        </div>
    </div>

    <div class="row d-flex justify-content-center">
        <div class="col-10">
            <form method="POST" action="{% url 'add_post' %}" class="form mb-2" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                {% if field.name != 'image' %}
                {{ field | as_crispy_field }}
                {% else %}
                {{ field }}
                {% endif %}
                {% endfor %}
                <div class="text-right">
                    <a class="btn btn-red rounded-0" href="{% url 'blog' %}">Cancel</a>
                    <button class="btn btn-theme-color rounded-0" type="submit">Add Post</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
<script>
    $('#new-image').change(function () {
        var file = $('#new-image')[0].files[0];
        $('#filename').text(`Image will be set to: ${file.name}`);
    });
</script>
{% endblock %}

blog/templates/blog/all_posts.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
<!--
<div class="container">
    <div class="row">
        <div class="col text-center mt-3">
            <h2 class="page-heading-font">The Outdoor World Equipment and Adventure Blog</h2>
            <h5 class="text-muted">Share your product and adventure reviews</h5>
            <hr>
        </div>
    </div>
    {% for post in posts %}
    <div class="row d-flex justify-content-center mb-4">
        <div class="col-10">
            <div class="card">
                <div class="card-header bg-lightblue">
                    <h5 class="card-title card-title-font text-white" href="{% url 'post_detail' post.id %}">
                        <i class="fab fa-telegram"></i> {{ post.title }}</h5>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-2">                  
                            {% if post.image %}
                                <a href="{% url 'post_detail' post.id %}">
                                    <img class="card-img-top img-fluid" src="{{ post.image.url }} " alt=" {{ post.name }}">
                                </a>

                                {% elif post.image_url %}
                                    <a href="{% url 'post_detail' post.id %}">
                                        <img class="card-img-top img-fluid" src="{{ post.image_url }} " alt=" {{ post.name }}">
                                    </a>

                                {% else %}
                                    <a href="{% url 'post_detail' post.id %}">
                                        <img class="card-img-top img-fluid" src="{{ MEDIA_URL }}base-images/no-image.png" alt="{{ post.name }}">
                                    </a>
                            {% endif %}
                        </div>  
                        <div class="col-10">
                            <p class="card-text mb-auto">{{ post.content|slice:"150" }}</p>
                            <a href="{% url 'post_detail' post.id %}"><small>read more...</small></a>
                        </div>
                    </div>
                </div>
                <div class="card-footer bg-transparent">
                    <small class="text-muted">Posted on: {{ post.created_on }} by {{ post.author }}</small>
                </div>
            </div>
        </div>
    </div>
<hr>
{% endfor %}
</div>

-->

{% endblock %}

blog/templates/blog/blog.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
<div class="container mb-4">
    <div class="row d-flex justify-content-center">
        <div class="col">
            <h2 class="page-heading-font text-center">The Outdoor Blog</h2>
            <hr>
        </div>
    </div>

    {% for post in posts %}
    <div class="container d-flex justify-content-center">
        <div class="card-deck w-75">
            <div class="card mb-2">
                <div class="card-body">
                    <h5 class="card-title text-center"><i class="fab fa-telegram"></i> {{ post.title }}</h5>
                    <p class="card-text text-center">{{ post.body|slice:"150" }}....<a
                            href="{% url 'post_detail' post.id %}" class="text-link"> read more</a></p>
                </div>
                <div class="card-footer">
                    <small class="text-muted">Posted on: {{ post.date_added }}</small>
                    {% if request.user.is_superuser %}
                    <small class="float-right">
                        <a href="{% url 'edit_post' post.id %}"><i class="far fa-edit"></i>Edit </a>
                        <span>|</span>
                        <a class="text-danger" href="{% url 'delete_post' post.id %}"><i class="far fa-trash-alt"></i>
                            Delete</a>
                    </small>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

blog/templates/blog/edit_post.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
<div class="container mb-4">
    <div class="row d-flex justify-content-center">
        <div class="col">
            <h2 class="page-heading-font text-center">Edit Post</h2>
            <hr>
        </div>
    </div>

    <div class="row d-flex justify-content-center">
        <div class="col-lg-6 col-md-10 mt-3">
            <form method="POST" action="{% url 'edit_post' post.id %}" class="form mb-2" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form | crispy }}
                <div class="text-right">
                    <a class="btn btn-red rounded-0" href="{% url 'blog' %}">Cancel</a>
                    <button class="btn btn-theme-color rounded-0" type="submit">Edit Post</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
<script>
    $('#new-image').change(function () {
        var file = $('#new-image')[0].files[0];
        $('#filename').text(`Image will be set to: ${file.name}`);
    });
</script>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
<div class="container mb-4">
    <div class="row d-flex justify-content-center">
        <div class="col">
            <h2 class="page-heading-font text-center">The Outdoor Blog</h2>
            <hr>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-10">
            <div class="card text-center mb-4">
                <div class="card-header">
                    <h5><i class="fab fa-telegram"></i> {{ post.title }}</h5>
                </div>
                <div class="card-body">

                    {% if post.image %}
                    <img class="card-img-top img-fluid" src="{{ MEDIA_URL }}{{ post.image }}"
                        alt="Image for blog post:{{ post.title }}">

                    {% elif post.image_url %}
                    <img class="card-img-top img-fluid" src="{{ post.image_url }} "
                        alt="Image for blog post:{{ post.title }}">

                    {% else %}

                    {% endif %}

                    <p class="card-text">{{ post.body }}</p>
                </div>
                <div class="card-footer text-muted">
                    Posted on: <i class="far fa-calendar-alt"></i> {{ post.date_added }}
                    <p class="pt-2 comment-function-buttons">
                        <button class="btn btn-theme-color">
                            <a class="p-1" data-toggle="collapse" data-target="#collapseComments" aria-expanded="false"
                                aria-controls="collapseComments">
                                {% if comment_count == 1 %}
                                {{ comment_count }} Comment <i class="fas fa-comments"></i></a>
                            {% else %}
                            {{ comment_count }} Comments <i class="fas fa-comments"></i></a>
                            {% endif %}
                        </button>
                        <button class="btn btn-theme-color">
                            <a data-toggle="collapse" data-target="#collapseAddComments" aria-expanded="false"
                                aria-controls="collapseAddComments">
                                Add Comment <i class="fas fa-comment-medical p-1"></i></a>
                        </button>
                    </p>

                    {% if request.user.is_superuser %}
                    <small>
                        <a href="{% url 'edit_post' post.id %}"><i class="far fa-edit"></i>Edit </a>
                        <span>|</span>
                        <a class="text-danger" href="{% url 'delete_post' post.id %}"><i class="far fa-trash-alt"></i>
                            Delete</a>
                    </small>
                    {% endif %}

                </div>
                <div class="collapse" id="collapseComments">
                    <div class="row justify-content-center m-4">
                        <div class="col-10">
                            <div class="text-left">
                                {% for comment in comments %}
                                <div class="media">
                                    <i class="fas fa-4x fa-user-circle pull-left p-2"></i>
                                    <div class="media-body">
                                        <strong class="media-heading">{{ comment.name }}</strong>
                                        <p>{{ comment.body }}</p>
                                        <small><i class="far fa-calendar-alt"></i> {{ comment.date_added }}</small>
                                        {% if request.user.is_superuser %}
                                        <hr>
                                        <a class="text-danger" href="{% url 'delete_comment' comment.id %}">
                                            <i class="far fa-trash-alt"></i> Delete</a>
                                        </small>
                                        {% endif %}
                                    </div>
                                </div>

                                {% empty %}

                                <div class="notification">
                                    <i class="fas fa-comment-slash"></i>
                                    <p> No Comments Yet!</p>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="collapse" id="collapseAddComments">
                    <div class="justify-content-center m-4">
                        {% if new_comment %}
                        <div class="alert alert-success" role="alert">
                            Your comment is awaiting moderation
                        </div>

                        {% else %}
                        <i class="far fa-comment-dots mb-4"></i> <strong> Post a comment:</strong></i>
                        <form id="add_comment" action="." method="post">
                            {% csrf_token %}
                            <p><label for="id_name"></label> <input placeholder="Name:" size="81" type="text"
                                    name="name" maxlength="255" required="" id="id_name"></p>
                            <p><label for="id_email"></label> <input placeholder="Email:" size="81" type="email"
                                    name="email" maxlength="255" required="" id="id_email"></p>
                            <p><label for="id_body"></label> <textarea placeholder="Comment:" name="body" cols="80"
                                    rows="10" required="" id="id_body"></textarea></p>
                            <div class="field">
                                <div class="control">
                                    <button class="btn btn-theme-color is-success">Submit</button>
                                </div>
                            </div>
                        </form>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}